<?php
    class Ibarah_model extends CI_MODEL{
        public function kalimat(){
            $data = [
                $this->data_kalimat("1", "1", "أَنَا جُوْعَانُ", "Saya lapar", "kenyang gerogi", "شَبْعانُ مُرْتَبِكٌ"),
                $this->data_kalimat("2", "1", "أَنَا شَبْعانُ", "Saya kenyang", "gerogi ngambek", "مُرْتَبِكٌ مُسْتَسْلِمٌ"),
                $this->data_kalimat("3", "1", "أَنَا مُرْتَبِكٌ", "Saya gerogi", "pelupa kalah", "سَرِيعُ جَبَانٌ"),
                $this->data_kalimat("4", "1", "أَنَا مُوافِقٌ", "Saya setuju", "ngambek pelupa", "حُمَّي مَهْزُوْمٌ"),
                $this->data_kalimat("5", "1", "أَنَا زَعْلانُ", "Saya ngambek", "pemalas tersentuh", "أَسْتَحْيِيْ مُجْتَهِدٌ"),
                $this->data_kalimat("6", "1", "أَنَا مُسْتَسْلِمٌ", "Saya menyerah", "kalah pengecut", "مُتَأَثِّرٌ مُرْتَبِكٌ"),
                $this->data_kalimat("7", "1", "لَدَيَّ حُمَّي", "Saya demam", "pemalas sumpek", "كَسْلانُ مُخْتَنِقٌ"),
                $this->data_kalimat("8", "1", "أَنَا سَرِيعُ النِسْيانِ", "Saya pelupa", "pemalas menyerah", "مُسْتَسْلِمٌ"),
                $this->data_kalimat("9", "1", "أنْتَ كَسْلانُ", "Kamu pemalas", "rajin setuju", "مُوافِقٌ مُخْتَنِقٌ"),
                $this->data_kalimat("10", "1", "أَنَا مُجْتَهِدٌ جِدًّا", "Saya rajin banget", "malu", "مَهْزُوْمٌ"),
                $this->data_kalimat("11", "1", "أَنَا مُتَأَثِّرٌ", "Saya tersentuh", "gerogi setuju", "مُسْتَسْلِمٌ شَبْعانُ"),
                $this->data_kalimat("12", "1", "أَنَا أَسْتَحْيِيْ", "Saya malu", "setuju lapar", "مُوافِقٌ مُخْتَنِقٌ"),
                $this->data_kalimat("13", "1", "أنْتَ مَهْزُوْمٌ", "Kamu kalah", "pemalas pengecut", "جَبَانٌ كَسْلانُ"),
                $this->data_kalimat("14", "1", "أَنَا مُخْتَنِقٌ", "Saya sumpek", "kalah pengecut", "مُتَأَثِّرٌ مُرْتَبِكٌ"),
                $this->data_kalimat("15", "1", "أنْتَ جَبَانٌ", "Kamu pengecut", "kenyang gerogi", "شَبْعانُ مُرْتَبِكٌ"),

                
                $this->data_kalimat("16", "2", "أَنَا مُتَفاجِئٌ", "Saya kaget", "penasaran pusing", "عَطْشانُ جَادٌّ"),
                $this->data_kalimat("17", "2", "أَنَا مُسْتَسْلِمٌ", "Saya kapok", "penasaran pusing", "عَطْشانُ جَادٌّ"),
                $this->data_kalimat("18", "2", "أَنَا مُتَحَيِّرٌ", "Saya bingung", "penasaran pusing", "عَطْشانُ جَادٌّ"),
                $this->data_kalimat("19", "2", "أَنَا مُتْعَبٌ جِدًّا", "saya capek banget", "penasaran pusing", "عَطْشانُ جَادٌّ"),
                $this->data_kalimat("20", "2", "أَنَا زَلَّةُ لِسَانٍ", "Saya keceplosan", "lemot tertangkap", "بَطِيءٌ مَصْدُوعٌ"),
                $this->data_kalimat("21", "2", "أنْتَ مَقْبُوضٌ", "Kamu tertangkap", "PD menang", "فائِزٌ بَطِيءٌ"),
                $this->data_kalimat("22", "2", "أَنَا فُضُوْلِيٌّ", "Saya penasaran", "lemot tertangkap", "بَطِيءٌ مَصْدُوعٌ"),
                $this->data_kalimat("23", "2", "أَنَا عَطْشانُ", "Saya haus", "lemot tertangkap", "بَطِيءٌ مَصْدُوعٌ"),
                $this->data_kalimat("24", "2", "أَنَا رَاضِي", "Saya puas", "lemot tertangkap", "بَطِيءٌ مَصْدُوعٌ"),
                $this->data_kalimat("25", "2", "أَنَا مُسْتَعْجِلٌ", "Saya terburu-buru", "PD menang", "فائِزٌ بَطِيءٌ"),
                $this->data_kalimat("26", "2", "أَنَا مَصْدُوعٌ", "Saya pusing", "PD menang", "فائِزٌ بَطِيءٌ"),
                $this->data_kalimat("27", "2", "أنْتَ بَطِيءٌ", "Saya lemot", "penasaran pusing", "عَطْشانُ جَادٌّ"),
                $this->data_kalimat("28", "2", "أنا فائِزٌ", "Saya menang", "lemot tertangkap", "بَطِيءٌ مَصْدُوعٌ"),
                $this->data_kalimat("29", "2", "أَنَا وَاثِقٌ  مِنْ نَفْسِيْ", "Saya PD", "lemot tertangkap"),
                $this->data_kalimat("30", "2", "أنا جَادٌّ", "Saya serius", "PD menang", "فائِزٌ بَطِيءٌ"),

                $this->data_kalimat("31", "3", "أنا مُحْبِطٌ", "Saya frustrasi", "frustrasi pemberani", "شُجَاعٌ خائِفٌ"),
                $this->data_kalimat("32", "3", "أنْتَ شُجَاعٌ", "Kamu pemberani", "menggemaskan lebay", "مُخْجِلٌ لَطِيْفٌ"),
                $this->data_kalimat("33", "3", "أَنَا خائِفٌ", "Saya takut", "menggemaskan lebay", "مُخْجِلٌ لَطِيْفٌ"),
                $this->data_kalimat("34", "3", "أنْتَ مُجْرِمٌ", "Kamu penjahat", "frustrasi pemberani", "شُجَاعٌ خائِفٌ"),
                $this->data_kalimat("35", "3", "أنْتَ عَجِيْبٌ", "Kamu ada-ada saja", "frustrasi pemberani", "شُجَاعٌ خائِفٌ"),
                $this->data_kalimat("36", "3", "أنْتَ مُتَوَحِّشٌ", "Kamu kejam", "frustrasi pemberani", "شُجَاعٌ خائِفٌ"),
                $this->data_kalimat("37", "3", "أَنَا مُتَأكِّدٌ", "Saya yakin", "menggemaskan lebay", "مُخْجِلٌ لَطِيْفٌ"),
                $this->data_kalimat("38", "3", "أَنَا مُرْتاحٌ هُنا", "Saya betah disini", "takut", "خائِفٌ"),
                $this->data_kalimat("39", "3", "أَنْتَ مُخْجِلٌ", "Kamu malu-maluin", "frustrasi pemberani", "شُجَاعٌ خائِفٌ"),
                $this->data_kalimat("40", "3", "أَنْتَ لَطِيْفٌ", "Kamu menggemaskan", "frustrasi pemberani", "شُجَاعٌ خائِفٌ"),
                $this->data_kalimat("41", "3", "أَنْتَ مُبالِغٌ", "Kamu lebay", "frustrasi pemberani", "شُجَاعٌ خائِفٌ"),
                $this->data_kalimat("42", "3", "أَنَا مُتَفَهِّمٌ", "Saya pengertian", "frustrasi pemberani", "شُجَاعٌ خائِفٌ"),
                $this->data_kalimat("43", "3", "أنتَ مُسْتَقِلٌّ", "Kamu mandiri", "menggemaskan lebay", "مُخْجِلٌ لَطِيْفٌ"),
                $this->data_kalimat("44", "3", "أَنْتَ أنانِيٌّ", "Kamu egois", "menggemaskan lebay", "مُخْجِلٌ لَطِيْفٌ"),
                $this->data_kalimat("45", "3", "أنتَ مُمْتِعٌ", "Kamu menyenangkan", "menggemaskan lebay", "مُخْجِلٌ لَطِيْفٌ"),

                $this->data_kalimat("46", "4", "ابْتَعِدْ عَنِ التَدْخِينِ قَدْرَ اْلإِمْكَانِ", "Jauhilah rokok sebisa mungkin!"),
                $this->data_kalimat("47", "4", "قُلْ بِصَرَاحَةٍ", "Katakan dengan terus terang!", "", "ابْتَعِدْ عَنِ"),
                $this->data_kalimat("48", "4", "احْفَظُوْا ظَهْرًا عَنْ غَيْبٍ", "Hafalkan di luar kepala!"),
                $this->data_kalimat("49", "4", "أَصْلِحْ غِلْطَتَكَ", "Perbaiki kesalahanmu!", "bahasamu! ucapanmu!", "لُغَتَكَ كَلامِي"),
                $this->data_kalimat("50", "4", "مارِسْ لُغَتَكَ", "Praktekkan bahasamu!", "ucapanmu!", "كَلامِي"),
                $this->data_kalimat("51", "4", "أَيْقِظْنِيْ في الساعةِ الثالِثةِ صَبَاحًا", "Bangunkan saya jam tiga pagi!"),
                $this->data_kalimat("52", "4", "أغْلِقِ البَابَ", "Tutup pintunya!", "Ikuti ucapanku!", "قَلِّدْ كَلامِي"),
                $this->data_kalimat("53", "4", "اُدْخُلْ فِي الطَّابُورِ", "Antri dong!", "Hati-hati jalan!", "الطَّرِيْقِ"),
                $this->data_kalimat("54", "4", "تَنَبَّهْ فِي الطَّرِيْقِ", "Hati-hati di jalan!", "Pergilah", "الطَّابُورِ"),
                $this->data_kalimat("55", "4", "قَلِّدْ كَلامِي", "Ikuti ucapanku!", "Tutup pintunya!", "أغْلِقِ البَابَ"),

                $this->data_kalimat("56", "5", "كَرِّرْ مَرَّةً ثَانِيةً", "Ulangi lagi!", "Sekali", "أُخْرَى"),
                $this->data_kalimat("57", "5", "مَرّةً أُخْرَى", "Sekali lagi!", "Ulangi", "ثَانِيةً كَرِّرْ"),
                $this->data_kalimat("58", "5", "اُبْسُطِ البِسَاطَ", "Bukalah karpetnya!", "Lipatlah", "اِطْوِ"),
                $this->data_kalimat("59", "5", "اِطْوِ البِساطَ", "Lipatlah karpetnya!", "Bukalah", "اُبْسُطِ"),
                $this->data_kalimat("60", "5", "اِحْذَرْ", "Awas!", "Ingatkan saya!", "نَبِّهْنِي صَفِّقُوا"),
                $this->data_kalimat("61", "5", "نَبِّهْنِي", "Ingatkan saya!", "Awas!", "صَفِّقُوا اِحْذَرْ"),
                $this->data_kalimat("62", "5", "صَفِّقُوا", "Tepuk tangan!", "Tolong! Awas!", "نَبِّهْنِي مِنْ فَضْلِكَ"),
                $this->data_kalimat("63", "5", "أطْفِئِ اللَّمْبَةَ", "Matikan lampu!", "Nyalakan Tolong", "اِفْتَحِ"),
                $this->data_kalimat("64", "5", "اِفْتَحِ اللَّمْبَةَ", "Nyalakan lampu!", "Matikan Tolong", "أطْفِئِ"),
                $this->data_kalimat("65", "5", "اِغْتَسِلْ أوَّلا", "Mandi dulu!", "Awas!", "مَرَّةً اِفْتَحِ"),
                $this->data_kalimat("66", "5", "مِنْ فَضْلِكَ", "Tolong!", "Awas!", "مَرَّةً اِفْتَحِ"),
                $this->data_kalimat("67", "5", "اُحْضُرْ لِيْ الكِتَابَ", "Ambilkan saya buku!", "lampu!", "مِنْ فَضْلِكَ"),
                $this->data_kalimat("68", "5", "اِفْتَحِ البَابَ", "Bukalah pintunya!", "lampu!", "اللَّمْبَةَ"),
                $this->data_kalimat("69", "5", "شَارِكْ مَعِي", "Ikutlah bersamaku!", "Mandi dulu!", "اِغْتَسِلْ أوَّلا"),
                $this->data_kalimat("70", "5", "نَظِّفْ غُرْفَتَكَ", "Bersihkan kamarmu!", "Tolong! Awas!", "فَضْلِكَ الكِتَابَ"),

                $this->data_kalimat("71", "6", "اُكْنُسِ السَّاحَةَ", "Sapulah halamannya!", "teras! kamar!", "غُرْفَتَكَ لَحْظَةً"),
                $this->data_kalimat("72", "6", "اِنْتَظِرْ لَحْظَةً", "Tunggu sebentar!", "Doakan saya!", "اُكْنُسِ اِنْتَظِرْ"),
                $this->data_kalimat("73", "6", "اُدْعُ لي", "Doakan saya!", "Silahkan mampir!", "تَفَضَّلْ عِنْدِيْ"),
                $this->data_kalimat("74", "6", "تَفَضَّلْ عِنْدِيْ", "Silahkan mampir!", "Doakan saya!", "أَنَا مُنْتَعِشٌ"),
                $this->data_kalimat("75", "6", "تَوَقَّفْ عِنْدَنَا", "Silahkan mampir!", "Sapulah halamannya!", "اُكْنُسِ السَّاحَةَ"),
                $this->data_kalimat("76", "6", "أَنَا مُنْتَعِشٌ", "Aku merasa segar", "lelah geli", "شَعُرْتُ بِالْـجُوْعِ"),
                $this->data_kalimat("77", "6", "شَعُرْتُ بِالدَّغْدَغَةِ", "Aku merasa geli", "segar sehat", "مُنْتَعِشٌ بِالْمَلَلِ"),
                $this->data_kalimat("78", "6", "شَعُرْتُ بِالْـجُوْعِ", "Aku merasa lapar", "segar sehat", "مُنْتَعِشٌ بِالْمَلَلِ"),
                $this->data_kalimat("79", "6", "شَعُرْتُ بِالْمَلَلِ", "Aku merasa bosan", "segar sehat", "مُنْتَعِشٌ بِالْمَلَلِ"),
                $this->data_kalimat("80", "6", "شَعُرْتُ بِالغِيْرَةِ", "Aku merasa cemburu", "segar sehat", "مُنْتَعِشٌ بِالْمَلَلِ"),
                $this->data_kalimat("81", "6", "شَعُرْتُ بِاْلألَمِ فِي كُلِّ جَسَدِيْ", "Aku merasa sakit di seluruh badan"),
                $this->data_kalimat("82", "6", "اِشْتَرِ لي رَصيدًا", "Belikan saya pulsa!", "makanan! minuman!", "رَصيدًا تَفَضَّلْ"),
                $this->data_kalimat("83", "6", "أَنْهِ الطَّعَامَ", "Habiskan makanannya!", "minumannya! kuenya!", "رَصيدًا تَفَضَّلْ"),
                $this->data_kalimat("84", "6", "أَبْطِئْ فِي مَشْيِكَ", "Pelan-pelan dong jalannya!", "Cepetan", "أَسْرِعْ"),
                $this->data_kalimat("85", "6", "أَسْرِعْ في مَشْيِكَ", "Cepetan dong jalannya!", "Pelan-pelan", "أَبْطِئْ"),

                $this->data_kalimat("86", "7", "خَيْرٌ لَكَ أَنْ تَسْكُتَ", "Sebaiknya kamu diam", "pergi tidur", "تَوَقَّفْ"),
                $this->data_kalimat("87", "7", "دَعْنِي أَنْ أَسْتَرِيْحَ أوَّلًا", "Biarkan saya beristirahat", "sendiri pergi"),
                $this->data_kalimat("88", "7", "اِبْتَعِدْ عَنِّيْ", "Menjauhlah dariku!", "Mendekatlah denganku!", "اِقْتَرِبْ مِنِّي"),
                $this->data_kalimat("89", "7", "اِقْتَرِبْ مِنِّي", "Mendekatlah denganku!", "Menjauhlah dariku!", "اِبْتَعِدْ عَنِّيْ"),
                $this->data_kalimat("90", "7", "مَاذَا أَصَابَكَ", "Kamu sakit apa", "makan minum", "الإسْهَالُ الحُمَّى"),
                $this->data_kalimat("91", "7", "أَصَابَنِيَ الإسْهَالُ", "Saya sakit mencret", "demam pilek", "الحُمَّى الزُّكَامُ"),
                $this->data_kalimat("92", "7", "أَصَابَنِيَ الحُمَّى", "Saya sakit demam", "mencret pilek", "الإسْهَالُ الزُّكَامُ"),
                $this->data_kalimat("93", "7", "أَصَابَنِيَ الزُّكَامُ", "Saya pilek", "sariawan sudah sembuh", "الإسْهَالُ الزُّكَامُ"),
                $this->data_kalimat("94", "7", "أصابَنِيَ القُلَاعُ", "Saya sakit sariawan", "mencret pilek", "الإسْهَالُ الزُّكَامُ"),
                $this->data_kalimat("95", "7", "أصابَنِيَ الدُّمَلُ", "Saya bisulan", "mencret pilek", "الإسْهَالُ الزُّكَامُ"),
                $this->data_kalimat("96", "7", "أصابَنِيَ السُّعالُ", "Saya batuk", "mencret pilek", "الإسْهَالُ الزُّكَامُ"),
                $this->data_kalimat("97", "7", "مَعِيَ مَغْصٌ", "Saya sakit perut", "mencret pilek", "الإسْهَالُ الزُّكَامُ"),
                $this->data_kalimat("98", "7", "هَلْ شُفِيْتَ", "Apa kamu sudah sembuh", "mencret pilek", "الإسْهَالُ الزُّكَامُ"),
                $this->data_kalimat("99", "7", "شَفاك اللهُ", "Semoga cepat sembuh", "mencret pilek", "الإسْهَالُ الزُّكَامُ"),
                $this->data_kalimat("100", "7", "الحَمْدُ للهِ تَحَسَّنْتُ قَلِيْلًا", "Alhamdulillah agak lebih baik", "mencret pilek", "الإسْهَالُ الزُّكَامُ"),

                $this->data_kalimat("101", "8", "اِرْفَعْ صَوْتَكَ", "Keraskan suaramu!", "tendaganmu! pukulanmu!", "اِخْفِضْ بِصَوتٍ"),
                $this->data_kalimat("102", "8", "اِخْفِضْ صَوْتَكَ", "Pelankan suaramu!", "tendaganmu! pukulanmu!", "مُنْخَفِضٍ بِصَوتٍ"),
                $this->data_kalimat("103", "8", "تَكَلَّمْ بِصَوتٍ مُنْخَفِضٍ", "Bicaralah dengan suara pelan!", "", "تَقَدَّمْ بِصَوتٍ"),
                $this->data_kalimat("104", "8", "خُذْ راحَتَكَ", "Santai aja lagi!", "Geser sedikit!", "اِخْفِضْ بِصَوتٍ"),
                $this->data_kalimat("105", "8", "اِبْتَعِدْ قَلِيْلًا", "Geser sedikit!", "Maju sedikit!", "تَقَدَّمْ بِصَوتٍ"),
                $this->data_kalimat("106", "8", "تَقَدَّمْ قَلِيْلًا", "Maju sedikit!", "Mundur sedikit!", "اِبْتَعِدْ بِصَوتٍ"),
                $this->data_kalimat("107", "8", "اِرْجِعْ قَلِيْلًا", "Mundur sedikit!", "Penyakit keturunan", "وَرَاثِيٌّ مُعْدِي الطَّبِيْبَ"),
                $this->data_kalimat("108", "8", "مَرَضٌ وَرَاثِيٌّ", "Penyakit keturunan", "Penyakit menular", "مُعْدِي الطَّبِيْبَ"),
                $this->data_kalimat("109", "8", "مَرَضٌ مُعْدِي", "Penyakit menular", "Penyakit keturunan", "وَرَاثِيٌّ الطَّبِيْبَ"),
                $this->data_kalimat("110", "8", "هَلْ قَابَلْتَ الطَّبِيْبَ", "Apakah kamu sudah ke dokter", "", "وَرَاثِيٌّ مُعْدِي"),
                $this->data_kalimat("111", "8", "شَعُرْتُ بِالْوَحْدَةِ", "Aku merasa kesepian", "kedinginan kepanasan", "بِالبُرُوْدَةِ بِالْحَرَارَةِ"),
                $this->data_kalimat("112", "8", "شَعُرْتُ بِالبُرُوْدَةِ", "Aku merasa kedinginan", "kesepian kepanasan", "بِالْوَحْدَةِ بِالْحَرَارَةِ"),
                $this->data_kalimat("113", "8", "شَعُرْتُ بِالْحَرَارَةِ", "Aku merasa kepanasan", "kesepian kedinginan", "بِالبُرُوْدَةِ بِالْوَحْدَةِ"),
                $this->data_kalimat("114", "8", "هَذِهِ اللَّيْلَةَ", "Nanti malam", "siang sore", "بِالبُرُوْدَةِ بِالْوَحْدَةِ"),
                $this->data_kalimat("115", "8", "لَيْلَةَ أَمْسِ", "Kemarin malam", "pagi siang", "بِالبُرُوْدَةِ بِالْوَحْدَةِ"),

                $this->data_kalimat("116", "9", "هَذِهِ فِكْرَةٌ جَيِّدَةٌ", "Ini ide bagus", "masalah mudah", "تَفَضَّلْ"),
                $this->data_kalimat("117", "9", "تَفَضَّلْ", "Silahkan", "jangan cepat pergi!", "عِلَاوَةً عَلَى ذَلِكَ"),
                $this->data_kalimat("118", "9", "مِنْ فَضْلِكَ", "Silahkan", "jangan cepat pergi!", "عِلَاوَةً عَلَى ذَلِكَ"),
                $this->data_kalimat("119", "9", "عِلَاوَةً عَلَى ذَلِكَ", "Apalagi", "ide bagus", "تَفَضَّلْ"),
                $this->data_kalimat("120", "9", "أَثْنَاءَ الدِّرَاسَةِ", "Tengah pelajaran", "Ini ide bagus", "لَا أَحَدَ"),
                $this->data_kalimat("121", "9", "فَقَطْ/ فَحَسْبُ", "Saja", "Ini ide bagus kemudian", "لَا أَحَدَ"),
                $this->data_kalimat("122", "9", "رُبَّـمَـا", "Barangkali", "Ini ide bagus", "لَا أَحَدَ شَيْءَ"),
                $this->data_kalimat("123", "9", "لَا بَأْسَ/ لَا شَيْءَ", "Gak apa-apa", "ada masalah", "لَا أَحَدَ شَيْءَ"),
                $this->data_kalimat("124", "9", "لَا أَحَدَ", "Tak seorangpun", "siapa saja", "لَا شَيْءَ"),
                $this->data_kalimat("125", "9", "مُهِمٌّ جِدًّا", "Penting banget", "tidak butuh", "لَا أَحَدَ شَيْءَ"),
                $this->data_kalimat("126", "9", "أَيْضًا", "Juga", "tetapi nanti kapanpun", "لَا أَحَدَ شَيْءَ"),
                $this->data_kalimat("127", "9", "نَعَمْ، حَاضِرْ", "Iya", "tidak selamat datang", "لَا أَحَدَ شَيْءَ"),
                $this->data_kalimat("128", "9", "شُكْرًا جَزِيْلاً", "Terima kasih banyak", "nanti", "لَا أَحَدَ شَيْءَ"),
                $this->data_kalimat("129", "9", "عَفْوًا", "Maaf", "jangan cepat segera", "لَا أَحَدَ شَيْءَ"),
                $this->data_kalimat("130", "9", "آسِفْ/ مَعْذِرَةً/ عَفْوًا", "Permisi", "segera terima kasih", "لَا أَحَدَ شَيْءَ"),

                $this->data_kalimat("131", "10", "طَيِّبْ، حَسَنًا", "ok", "segera terima kasih", "بِالتَّدْرِيْجِ مُؤَقَّتًا الآنَ"),
                $this->data_kalimat("132", "10", "حَقًّا/ أَكِيْد", "Sungguh", "segera terima kasih", "بِالتَّدْرِيْجِ مُؤَقَّتًا الآنَ"),
                $this->data_kalimat("133", "10", "فِي الحَقِيْقَةِ", "Sebenarnya", "segera terima kasih", "بِالتَّدْرِيْجِ مُؤَقَّتًا الآنَ"),
                $this->data_kalimat("134", "10", "طَبْعًا", "Tentu", "segera terima kasih", "بِالتَّدْرِيْجِ مُؤَقَّتًا الآنَ"),
                $this->data_kalimat("135", "10", "بِلاَ شَكٍّ", "Dengan tanpa ragu", "sungguh", "بِالتَّدْرِيْجِ مُؤَقَّتًا الآنَ"),
                $this->data_kalimat("136", "10", "مُؤَقَّتًا", "Sementara", "segera terima kasih selamanya", "بِالتَّدْرِيْجِ حَتَّى الآنَ"),
                $this->data_kalimat("137", "10", "مَرَّةً أُخْرَى", "Sekali lagi", "segera terima kasih dua kali", "بِالتَّدْرِيْجِ حَتَّى الآنَ"),
                $this->data_kalimat("138", "10", "بِالتَّدْرِيْجِ", "Secara bertahap", "sendiri terima kasih", "حَتَّى الآنَ"),
                $this->data_kalimat("139", "10", "شَيْئًا فَشَيْئًا", "sedikit demi sedikit", "segera terima kasih", "عَلَى حِسَابِيْ عِلَاوَةً"),
                $this->data_kalimat("140", "10", "قَلِيْلاً فَقَلِيْلاً", "sedikit demi sedikit", "segera terima kasih", "عَلَى حِسَابِيْ عِلَاوَةً"),
                $this->data_kalimat("141", "10", "حَتَّى الآنَ", "Hingga sekarang", "nanti padahal", "عَلَى حِسَابِيْ عِلَاوَةً"),
                $this->data_kalimat("142", "10", "بِالتَّأَنِّي", "Pelan-pelan", "cepat hati-hati", "عَلَى حِسَابِيْ عِلَاوَةً"),
                $this->data_kalimat("143", "10", "عَلَى مَسْؤُوْلِيَتِيْ", "Tanggung jawabku", "pelan-pelan hati-hati", "حِسَابِيْ عِلَاوَةً"),
                $this->data_kalimat("144", "10", "عَلَى حِسَابِيْ", "Saya yang traktir", "kamu dia", "عِلَاوَةً عَلَى هَذَا"),
                $this->data_kalimat("145", "10", "عِلَاوَةً عَلَى هَذَا", "Apalagi ini", "itu jangan", "عَلَى حِسَابِيْ"),

                $this->data_kalimat("146", "11", "خُصُوْصًا هَذَا", "Khususnya ini", "umumnya itu", "بِهَذِهِ الطَّرِيْقَةِ هَكَذَا"),
                $this->data_kalimat("147", "11", "بِسُهُوْلَةٍ", "Dengan mudah", "perjuangan kesulitan", "بِهَذِهِ الطَّرِيْقَةِ هَكَذَا"),
                $this->data_kalimat("148", "11", "بِصُعُوْبَةٍ", "Dengan sulit", "mudah kemudahan", "بِهَذِهِ الطَّرِيْقَةِ هَكَذَا"),
                $this->data_kalimat("149", "11", "عَلَى فَرْحَتِكْ/ كَمَا شِئْتَ", "Terserah kamu", "saya dia mereka", "بِهَذِهِ الطَّرِيْقَةِ"),
                $this->data_kalimat("150", "11", "بِهَذِهِ الطَّرِيْقَةِ", "Dengan cara ini", "contoh itu", "هَذَا مُـمْكِنٌ"),
                $this->data_kalimat("151", "11", "بِدُوْنِ اسْتِثْنَاءٍ", "Tanpa terkecuali", "selamanya", "بِهَذِهِ الطَّرِيْقَةِ"),
                $this->data_kalimat("152", "11", "هَكَذَا", "Begini lo", "itu hati-hati", "أَحْسَنُ هَذَا مُـمْكِنٌ"),
                $this->data_kalimat("153", "11", "هَذَا مُـمْكِنٌ", "Ini mungkin", "itu tidak", "هَكَذَا أَحْسَنُ"),
                $this->data_kalimat("154", "11", "هَذَا أَحْسَنُ", "Ini bagus", "jelek tidak", "لَا تُشْغِلْ مُـمْكِنٌ"),
                $this->data_kalimat("155", "11", "هَذَا شَيْءٌ ظَاهِرٌ", "Ini sesuatu yang nampak", "tidak", "لَا تُشْغِلْ نَفْسَكْ"),
                $this->data_kalimat("156", "11", "لَا تُشْغِلْ نَفْسَكْ", "Jangan repot-repot", "sungkan buru-buru", "بِقَدْرِ الاِسْتِطَاعَةِ"),
                $this->data_kalimat("157", "11", "بِقَدْرِ الاِسْتِطَاعَةِ", "Sebisanya", "mungkin Tanpa terkecuali", "الاِمْكَانِ مَشْغُولٌ"),
                $this->data_kalimat("158", "11", "بِقَدْرِ الاِمْكَانِ", "Sebisa mungkin", "Jangan terburu-buru", "الاِسْتِطَاعَةِ مَشْغُولٌ"),
                $this->data_kalimat("159", "11", "لاَ تَسْتَعْجِلْ", "Jangan terburu-buru", "pelit marah", "أَظُنُّ مَشْغُولٌ"),
                $this->data_kalimat("160", "11", "مَا أَجْمَلَهُ", "Betapa gantengnya dia", "pelit baik", "أَظُنُّ مَشْغُولٌ"),

                
                $this->data_kalimat("161", "12", "عَلَى مَا أَظُنُّ", "Seperti yang kukira", "Ini banyak banget", "إِذَا أَمْكَنَ"),
                $this->data_kalimat("162", "12", "أَنَا مَشْغُولٌ", "Saya repot", "Ini banyak banget", "إِذَا أَمْكَنَ"),
                $this->data_kalimat("163", "12", "هَذَا كَثِيْرٌ جِدًّا", "Ini banyak banget", "sedikit", "إِذَا أَمْكَنَ"),
                $this->data_kalimat("164", "12", "رَأَيْتُهُ عِيَانًا", "Saya melihat sendiri", "Seperti yang kukira", "مَشْغُولٌ أُصَدِّقُ"),
                $this->data_kalimat("165", "12", "لاَ أَعْرِفُ ذَلِكَ", "Saya gak tahu itu", "percaya", "أُصَدِّقُ"),
                $this->data_kalimat("166", "12", "لاَ أُصَدِّقُ ذَلِكَ", "Saya gak percaya itu", "Jika mungkin Biasanya", "عَادَةً بِدُوْنِ"),
                $this->data_kalimat("167", "12", "مِنَ الآنَ فَصَاعِدًا", "Dari sekarang dan seterusnya", "Jika mungkin Biasanya", "عَادَةً بِدُوْنِ"),
                $this->data_kalimat("168", "12", "بِكُلِّ فَرَحٍ وَ سُرُورٍ", "Dengan senang hati", "Saya percaya", "مِنَ الآنَ فَصَاعِدًا"),
                $this->data_kalimat("169", "12", "بِدُوْنِ عَمْدٍ", "Tanpa sengaja", "Biasanya senang hati", "إِذَا أَمْكَنَ"),
                $this->data_kalimat("170", "12", "عَادَةً", "Biasanya", "Tanpa sengaja Seperti", "إِذَا أَمْكَنَ بِدُوْنِ عَمْدٍ"),
                $this->data_kalimat("171", "12", "كَالعَادَةِ", "Seperti biasa", "Tanpa sengaja", "إِذَا أَمْكَنَ"),
                $this->data_kalimat("172", "12", "إِذَا أَمْكَنَ", "Jika mungkin", "Selamanya Biasanya", "عَادَةً بِدُوْنِ"),
                $this->data_kalimat("173", "12", "عَلَى الدَّوَامِ/ لِلْأَبَدِ", "Selamanya", "Jika mungkin Biasanya", "عَادَةً بِدُوْنِ"),
                $this->data_kalimat("174", "12", "غَالِبًا", "Sering", "Berkali-kali Awas Hati-hati", "مِرَارًا اِحْتَرِسْ اِنْتَبِهْ"),
                $this->data_kalimat("175", "12", "مِرَارًا", "Berkali-kali", "Pantesan Awas Hati-hati", "اِحْتَرِسْ اِنْتَبِهْ لَا عَجَبَ"),

                
                $this->data_kalimat("176", "13", "لَا عَجَبَ", "Pantesan", "Awas Hati-hati", "اِحْتَرِسْ اِنْتَبِهْ"),
                $this->data_kalimat("177", "13", "مُتَأَسِّفٌ جِدًّا", "Kasihan banget", "Selamat jalan", "جِدًّا عَجِيْبٌ"),
                $this->data_kalimat("178", "13", "هَا قَدْ جَاءَ", "Ini dia dah datang", "pergi kembali", "نَسْتَرِيْحُ نَخْرُجُ"),
                $this->data_kalimat("179", "13", "هَيَّا بِنَا نَخْرُجُ مَعًا", "Ayo keluar bareng", "pulang berangkat", "نَسْتَرِيْحُ"),
                $this->data_kalimat("180", "13", "هَيَّا بِنَا نَسْتَرِيْحُ", "Ayo istirahat", "pulang berangkat", "نَخْرُجُ اِهْتَمُّوْا"),
                $this->data_kalimat("181", "13", "أَيْنَ عُنْوَانُكَ", "Mana alamatmu", "rumahmu sekolahmu", "رِسَالَةٌ بَسِيْطٌ"),
                $this->data_kalimat("182", "13", "غَدًا أَوْ بَعْدَ غَدٍ", "besok atau besok lusa", "kemarin"),
                $this->data_kalimat("183", "13", "هَذَا الخَـبَرُ صَحِيْحٌ", "Berita ini benar", "hoax menakjubkan", "عَجِيْبٌ بَسِيْطٌ"),
                $this->data_kalimat("184", "13", "هَذَا الخَـبَرُ زَائِفٌ", "Berita ini hoax", "benar penting", "صَحِيْحٌ عَجِيْبٌ"),
                $this->data_kalimat("185", "13", "هَذَا أَمْرٌ مُهِمٌّ", "Ini hal penting", "sepele menakjubkan", "عَجِيْبٌ بَسِيْطٌ"),
                $this->data_kalimat("186", "13", "هَذَا أَمْرٌ بَسِيْطٌ", "Ini hal sepele", "menakjubkan", "عَجِيْبٌ"),
                $this->data_kalimat("187", "13", "هَذَا عَجِيْبٌ جِدًّا", "Ini menakjubkan", "hal sepele", "أَمْرٌ بَسِيْطٌ"),
                $this->data_kalimat("188", "13", "لَكَ رِسَالَةٌ قَصِيْرَةٌ", "Kamu dapat sms nih", "Berita", "الخَـبَرُ"),
                $this->data_kalimat("189", "13", "اُنْظُرْ اِلَيَّ", "Lihat saya", "Perhatikan Ayo", "اِهْتَمُّوْا عَجَبَ"),
                $this->data_kalimat("190", "13", "اِهْتَمُّوْا جَيِّدًا", "Perhatikan baik-baik", "Lihat", "اُنْظُرْ اِحْتَرِسْ"),

                
                $this->data_kalimat("191", "14", "أُحِبُّكَ", "Saya cinta kamu", "masih tidak", "اِنْتَبِهْ عَازِبًا تَدْخُلْ"),
                $this->data_kalimat("192", "14", "لَا تَنْسَ", "Jangan lupa", "pergi berisik", "اِنْتَبِهْ حَسَنًا"),
                $this->data_kalimat("193", "14", "مَا عِنْدِيْ وَقْتٌ", "Saya gak punya waktu", "uang", "عَازِبًا"),
                $this->data_kalimat("194", "14", "لَـمْ أَفْهَمْ مَا تُرِيْدُ", "Saya gak ngerti apa yang kamu mau"),
                $this->data_kalimat("195", "14", "أَحْتَاجُ إِلَى مُسَاعَدَتِكْ", "Saya butuh bantuanmu", "cinta kamu", "بِـمَعْرِفَتِكْ"),
                $this->data_kalimat("196", "14", "أَنَا فَرْحَانُ بِمُقَابَلَتِكَ", "Saya senang bertemu denganmu", "kenal", "مُتَشَرِّفٌ"),
                $this->data_kalimat("197", "14", "مُتَشَرِّفٌ بِـمَعْرِفَتِكْ", "Senang kenal denganmu", "bertemu", "مُبَاشَرَةً حَسَنًا"),
                $this->data_kalimat("198", "14", "اِنْتَبِهْ", "Hati-hati", "Awas Senang", "اِحْتَرِسْ مُبَاشَرَةً"),
                $this->data_kalimat("199", "14", "اِحْتَرِسْ", "Awas", "Hati-hati Langsung", "مُبَاشَرَةً اِنْتَبِهْ"),
                $this->data_kalimat("200", "14", "هَلْ عِنْدَكَ حَبِيْبَةٌ", "Apakah kamu punya kekasih", "cinta", "عَازِبًا"),
                $this->data_kalimat("201", "14", "مَازِلْتُ عَازِبًا", "Aku masih bujang", "cinta banget", "حَسَنًا جِدًّا"),
                $this->data_kalimat("202", "14", "حَسَنًا جِدًّا", "Bagus banget", "kekasih cinta", "عَازِبًا حَبِيْبَةٌ"),
                $this->data_kalimat("203", "14", "تَعَالْ بِسُرْعَةٍ", "Kesini! cepat", "Pergi! sana", "لَا تَنْسَ"),
                $this->data_kalimat("204", "14", "لَا تَدْخُلْ قَبْلَ السَّلاَمِ", "Jangan masuk sebelum salam", "pergi"),
                $this->data_kalimat("205", "14", "تَقَدَّمْ إِلَى الأَمَامِ", "Maju kedepan", "Pergi kebelakang", "تَدْخُلْ"),
                
                $this->data_kalimat("206", "15", "لَا تُدَغْدِغْنِيْ", "Jangan menggelitiki aku", "menakuti menyakiti", "تَتَدَخَّلْ تَـخَفْ"),
                $this->data_kalimat("207", "15", "لَا تَتَدَخَّلْ فِي أَمْرِيْ", "Jangan ikut campur", "aku", "مَعِيْ"),
                $this->data_kalimat("208", "15", "لَا تَحْزَنْ", "Jangan sedih", "marah takut", "تَغْضَبْ تَحْزَنْ"),
                $this->data_kalimat("209", "15", "لَا تَـخَفْ", "Jangan takut", "marah sedih", "تَغْضَبْ تَحْزَنْ"),
                $this->data_kalimat("210", "15", "لَا تَغْضَبْ", "Jangan marah", "takut sedih", "تَـخَفْ تَحْزَنْ"),
                $this->data_kalimat("211", "15", "أَنْتَ مِسْكِيْنُ", "Kamu kasihan", "marah takut", "تَغْضَبْ تَحْزَنْ"),
                $this->data_kalimat("212", "15", "لِمـَاذَا جِئْتَ مُتَأَخِّرًا", "Kenapa kamu terlambat", "berisik", "تُشَوِّشْ"),
                $this->data_kalimat("213", "15", "لَا تَمْزَحْ", "Jangan bercanda", "berisik", "تُشَوِّشْ"),
                $this->data_kalimat("214", "15", "لَا تُشَوِّشْ", "Jangan berisik", "bercanda", "تَمْزَحْ"),
                $this->data_kalimat("215", "15", "لَا تَكُنْ فُضُوْلِيًّا", "Jangan kepo deh", "bercanda", "تَمْزَحْ"),
                $this->data_kalimat("216", "15", "لَا تَرْمِ الزُّبَالَةِ فِي أَيِّ مَكَانٍ", "Jangan buang sampah sembarangan"),
                $this->data_kalimat("217", "15", "كَمْ مَرَّةً", "Berapa kali", "Dua", "مَرَّتَيْنِ"),
                $this->data_kalimat("218", "15", "مَرَّتَيْنِ", "Dua kali", "Berapa", "كَمْ مَرَّةً"),
                $this->data_kalimat("219", "15", "لاَ تَكُنْ كَذَلِكَ", "Jangan seperti itu", "lakukan"),
                $this->data_kalimat("220", "15", "لَا تَفْعَلْ ذَلِكَ", "Jangan lakukan seperti itu"),
                
                $this->data_kalimat("221", "16", "لَا تَضَعِ الأَشْيَاءَ هُنَا", "Jangan taruh sesuatu disini"),
                $this->data_kalimat("222", "16", "لَا تَـحْتَقِرْ الآخَرِيْنَ", "Jangan menghina orang lain", "saya", "شَيْءٍ"),
                $this->data_kalimat("223", "16", "لَا تَنْشُرْ الغِيْبَةَ", "Jangan sebar gosip", "kepo", "وَدَاعًا"),
                $this->data_kalimat("224", "16", "وَدَاعًا", "Selamat tinggal", "Langsung", "مُبَاشَرَةً الِّلقَاءِ"),
                $this->data_kalimat("225", "16", "أَنْتَ رَخِيْصٌ", "Kamu gak ada harganya", "Kurangi", "اُنْقُصْ قَلِيْلًا"),
                $this->data_kalimat("226", "16", "اُنْقُصْ قَلِيْلًا", "Kurangi dikit", "harganya", "أَنْتَ رَخِيْصٌ"),
                $this->data_kalimat("227", "16", "اُنْظُرْ هُنَا", "Lihat sini", "Gak ada apa2", "لاَ شَيْءٍ"),
                $this->data_kalimat("228", "16", "لاَ شَيْءٍ", "Gak ada apa2", "Lihat sini", "اُنْظُرْ هُنَا"),
                $this->data_kalimat("229", "16", "تَخَرَّجْتُ مِنْ", "Saya lulus dari", "Kurangi dikit", "لاَ شَيْءٍ"),
                $this->data_kalimat("230", "16", "تَحَرَّكْ قَلِيْلاً", "Geser dikit dong", "Lihat sini", "لاَ شَيْءٍ"),
                $this->data_kalimat("231", "16", "لَا أُبَالِي/ لَا أَهْتَمُّ", "Saya gak peduli", "Sama aja"),
                $this->data_kalimat("232", "16", "نَفْسُ الشَّيْءِ", "Sama aja", "Sampai jumpa", "إِلَى الِّلقَاءِ"),
                $this->data_kalimat("233", "16", "إِلَى الِّلقَاءِ", "Sampai jumpa", "Sama aja", "نَفْسُ الشَّيْءِ"),
                $this->data_kalimat("234", "16", "مَعَ السَّلاَمَةِ", "Sampai jumpa", "Tanpa mikir", "بِدُوْنِ تَفْكِيْرٍ"),
                $this->data_kalimat("235", "16", "بِدُوْنِ تَفْكِيْرٍ", "Tanpa mikir", "Sampai jumpa", "مَعَ السَّلاَمَةِ"),
                
                $this->data_kalimat("236", "17", "مُبَاشَرَةً", "Langsung", "Jangan bohong", "جِدًّا تُبْطِئْ مَعًا"),
                $this->data_kalimat("237", "17", "اِصْبِرْ يَا أَخِيْ", "Sabar bro", "Langsung", "مُبَاشَرَةً جِدًّا"),
                $this->data_kalimat("238", "17", "هَلْ تَسْمَعُ كَلَامِيْ", "Apakah kamu mendengar ucapanku", "", "تَسْتَطِيْعُ"),
                $this->data_kalimat("239", "17", "هَلْ تَسْتَطِيْعُ أَنْ تُسَاعِدَنِى", "Apakah kamu bisa membantuku"),
                $this->data_kalimat("240", "17", "هَيَّا تَعَالْ مَعِيْ", "Ayo ikut denganku", "pergi", "مُبَاشَرَةً"),
                $this->data_kalimat("241", "17", "لَا تُزْعِجْنِيْ", "Jangan ganggu aku", "lama-lama ikut", "تُبْطِئْ تَكْذِبْ"),
                $this->data_kalimat("242", "17", "لَا تُبْطِئْ", "Jangan lama-lama", "Langsung lapar", "جَائِعٌ جِدًّا"),
                $this->data_kalimat("243", "17", "أَنَا مُسْتَعِدٌّ", "Saya siap", "Langsung lapar", "جَائِعٌ جِدًّا"),
                $this->data_kalimat("244", "17", "أَنَا جَائِعٌ جِدًّا", "Saya lapar banget"),
                $this->data_kalimat("245", "17", "أُسْكُتُوْا كُلَّكُمْ", "Kalian semua diam!", "pergi", "مُبَاشَرَةً"),
                $this->data_kalimat("246", "17", "هَيَّا نَذْهَبُ مَعًا", "Ayo pergi bareng", "Saya siap"),
                $this->data_kalimat("247", "17", "رَائِعٌ جِدًّا", "Luar biasa sekali", "Aku", "عَلَيَّ"),
                $this->data_kalimat("248", "17", "لَا تَكْذِبْ عَلَيَّ", "Jangan bohongi aku"),
                $this->data_kalimat("249", "17", "مَا عِنْدِيْ فُلُوْسٌ", "Aku gak punya uang"),
                $this->data_kalimat("250", "17", "لَا اُرِيْدُ أَنْ اَسْمَعَ كَلَامَكْ", "Saya gak mau dengar ucapanmu"),
                
                $this->data_kalimat("251", "18", "لَا يُعْجِبُنْيْ كَثِيْرًا", "Saya gak terlalu suka"),
                $this->data_kalimat("252", "18", "لَا تَقْلَقْ", "Jangan khawatir", "ngomong", "تُكَثِّرِ"),
                $this->data_kalimat("253", "18", "لَا تُكَثِّرِ اْلكَلَامَ", "Jangan banyak ngomong", "istirahat", "الرَّاحَةَ"),
                $this->data_kalimat("254", "18", "لَا تَدُرْ حَوْلَ الْمَوْضُوْعَ", "Jangan bertele-tele", "ngomong istirahat"),
                $this->data_kalimat("255", "18", "أَحْتَاجُ الْمُسَاعَدَةْ", "Saya butuh bantuan", "istirahat", "الرَّاحَةَ"),
                $this->data_kalimat("256", "18", "أَحْتَاجُ الرَّاحَةَ", "Saya butuh istirahat", "bantuan", "الْمُسَاعَدَةْ"),
                $this->data_kalimat("257", "18", "حَقًّا اُرِيْدُ أَنْ أَذْهَبَ", "Saya benar2 pengen pergi"),
                $this->data_kalimat("258", "18", "أَنَا أَمْزَحْ فَحَسْبُ", "saya hanya bercanda", "istirahat", "اُرِيْدُ"),
                $this->data_kalimat("259", "18", "يَجِبُ عَلَيَّ أَنْ أَذْهَبَ", "Saya harus pergi", "istirahat", "الرَّاحَةَ"),
                $this->data_kalimat("260", "18", "لَا أُرِيْدُ أَنْ أَذْهَبَ اِلَى أَيِّ مَكَانٍ", "Saya tidak ingin pergi kemana-mana"),
                $this->data_kalimat("261", "18", "هَذَا غَيْرُ مُرِيْحٍ", "Ini gak enak", "saya bercanda", "أَمْزَحْ"),
                $this->data_kalimat("262", "18", "اُتْرُكْنِيْ وَحْدِيْ", "Tinggalkan aku sendiri", "istirahat", "مُرِيْحٍ غَيْرُ"),
                $this->data_kalimat("263", "18", "جَرِّبْ أَوَّلًا", "Coba dulu", "Jangan egois", "لَا تَكُنْ أَنَانِيًا"),
                $this->data_kalimat("264", "18", "عِنْدِيْ مُشْكِلَةٌ كَبِيْرَةٌ", "Saya punya masalah besar"),
                $this->data_kalimat("265", "18", "لَا تَكُنْ أَنَانِيًا", "Jangan egois", "Coba dulu", "جَرِّبْ أَوَّلًا"),

                $this->data_kalimat("266", "19", "مَنْ سَارَ عَلىَ الدَّرْبِ وَصَلَ", "Barang siapa berjalan pada jalannya sampailah ia"),
                $this->data_kalimat("267", "19", "مَنْ جَدَّ وَجَدَ", "Barang siapa bersungguh-sungguh, dapatlah ia"),
                $this->data_kalimat("268", "19", "مَنْ صَبَرَ ظَفِرَ", "Barang siapa sabar beruntunglah ia"),
                $this->data_kalimat("269", "19", "مَنْ قَلَّ صِدْقُهُ قَلَّ صَدِيْقُهُ", "Barang siapa sedikit benarnya/kejujurannya, sedikit pulalah temannya"),
                $this->data_kalimat("270", "19", "جَالِسْ أَهْلَ الصِّدْقِ وَالوَفَاءِ", "Pergaulilah orang yang jujur dan menepati janji"),
                $this->data_kalimat("271", "19", "مَوَدَّةُ الصَّدِيْقِ تَظْهَرُ وَقْتَ الضِّيْقِ", "Kecintaan/ketulusan teman itu, akan tampak pada waktu kesempitan"),
                $this->data_kalimat("272", "19", "وَ مَا اللَّذَّةُ إِلاَّ بَعْدَ التَّعَبِ", "Tidak kenikmatan kecuali setelah kepayahan"),
                $this->data_kalimat("273", "19", "الصَّبْرُ يُعِيْنُ عَلىَ كُلِّ عَمَلٍ", "Kesabaran itu menolong segala pekerjaan"),
                $this->data_kalimat("274", "19", "جَرِّبْ وَ لاَحِظْ تَكُنْ عَارِفًا", "Cobalah dan perhatikanlah, niscaya kau jadi orang yang tahu"),
                $this->data_kalimat("275", "19", "اُطْلُبِ العِلْمَ مِنَ المَهْدِ إِلىَ اللَّحْدِ", "Tuntutlah ilmu sejak dari buaian hingga liang kubur"),
                $this->data_kalimat("276", "19", "بَيْضَةُ اليَوْمِ خَيْرٌ مِنْ دَجَاجَةِ الغَدِ", "Telur hari ini lebih baik daripada ayam esok hari"),
                $this->data_kalimat("277", "19", "الوَقْتُ أَثْمَنُ مِنَ الذَّهَبِ", "Waktu itu lebih mahal daripada emas"),

                $this->data_kalimat("278", "20", "العَقْلُ السَّلِيْمُ فيِ الجِسْمِ السَّلِيْمِ", "Akal yang sehat itu terletak pada badan yang sehat"),
                $this->data_kalimat("279", "20", "خَيْرُ جَلِيْسٍ فيِ الزَّمَانِ كِتَابٌ", "Sebaik-baik teman duduk pada setiap waktu adalah buku"),
                $this->data_kalimat("280", "20", "مَنْ يَزْرَعْ يَحْصُدْ", "Barang siapa menanam pasti akan memetik"),
                $this->data_kalimat("281", "20", "خَيْرُ الأَصْحَابِ مَنْ يَدُلُّكَ عَلىَ الخَيْرِ", "Sebaik-baik teman itu ialah yang menunjukkan kamu kepada kebaikan"),
                $this->data_kalimat("282", "20", "لَوْلاَ العِلْمُ لَكَانَ النَّاسُ كَالبَهَائِمِ", "Seandainya tiada berilmu niscaya manusia itu seperti binatang"),
                $this->data_kalimat("283", "20", "العِلْمُ فيِ الصِّغَرِ كَالنَّقْشِ عَلىَ الحَجَرِ", "Ilmu pengetahuan diwaktu kecil itu, bagaikan ukiran di atas batu"),
                $this->data_kalimat("284", "20", "لَنْ تَرْجِعَ الأَياَّمُ الَّتيِ مَضَتْ", "Tidak akan kembali hari-hari yang telah berlalu"),
                $this->data_kalimat("285", "20", "تَعَلَّمْ صَغِيْرًا وَاعْمَلْ بِهِ كَبِيْرًا", "Belajarlah di waktu kecil dan amalkanlah di waktu besar"),
                $this->data_kalimat("286", "20", "العِلْمُ بِلاَ عَمَلٍ كَالشَّجَرِ بِلاَ ثَمَرٍ", "Ilmu tiada amalan bagaikan pohon tidak berbuah"),
                $this->data_kalimat("287", "20", "الاتِّحَادُ أَسَاسُ النَّجَاحِ", "Bersatu adalah pangkal keberhasila"),
                $this->data_kalimat("288", "20", "لاَ تَحْتَقِرْ مِسْكِيْنًا وَ كُنْ لَهُ مُعِيْناً", "Jangan engkau menghina orang miskin bahkan jadilah penolong baginya"),
                $this->data_kalimat("289", "20", "الشَّرَفُ بِالأَدَبِ لاَ بِالنَّسَبِ", "Kemuliaan itu dengan adab kesopanan, (budi pekerti) bukan dengan keturunan"),
                
                $this->data_kalimat("290", "21", "سَلاَمَةُ الإِنْسَانِ فيِ حِفْظِ اللِّسَانِ", "Keselamatan manusia itu dalam menjaga lidahnya (perkataannya)"),
                $this->data_kalimat("291", "21", "آدَابُ المَرْءِ خَيْرٌ مِنْ ذَهَبِهِ", "Adab seseorang itu lebih baik (lebih berharga) daripada emasnya"),
                $this->data_kalimat("292", "21", "سُوْءُ الخُلُقِ يُعْدِي", "Kerusakan budi pekerti/akhlaq itu menular"),
                $this->data_kalimat("293", "21", "آفَةُ العِلْمِ النِّسْياَنُ", "Bencana ilmu itu adalah lupa"),
                $this->data_kalimat("294", "21", "إِذَا صَدَقَ العَزْمُ وَضَحَ السَّبِيْلُ", "Jika benar kemauannya niscaya terbukalah jalannya"),
                $this->data_kalimat("295", "21", "لاَ تَحْتَقِرْ مَنْ دُوْنَكَ فَلِكُلِّ شَيْئٍ مَزِيَّةٌ", "Jangan menghina seseorang yang lebih rendah daripada kamu, karena segala sesuatu itu mempunyai kelebihan"),
                $this->data_kalimat("296", "21", "أَصْلِحْ نَفْسَكَ يَصْلُحْ لَكَ النَّاسُ", "Perbaikilah dirimu sendiri, niscaya orang-orang lain akan baik padamu"),
                $this->data_kalimat("297", "21", "فَكِّرْ قَبْلَ أَنْ تَعْزِمَ", "Berpikirlah dahulu sebelum kamu berkemauan"),
                $this->data_kalimat("298", "21", "مَنْ عَرَفَ بُعْدَ السَّفَرِ اِسْتَعَدَّ", "Barang siapa tahu jauhnya perjalanan, bersiap-siaplah ia"),
                $this->data_kalimat("299", "21", "مَنْ حَفَرَ حُفْرَةً وَقَعَ فِيْهَا", "Barang siapa menggali lobang, akan terperosoklah ia di dalamnya"),
                $this->data_kalimat("300", "21", "عَدُوٌّ عَاقِلٌ خَيْرٌ مِنْ صَدِيْقٍ جَاهِلٍ", "Musuh yang pandai, lebih baik daripada tenan yang bodoh"),
                
                $this->data_kalimat("301", "22", "مَنْ كَثُرَ إِحْسَانُهُ كَثُرَ إِخْوَانُهُ", "Barang siapa banyak perbuatan baiknya, banyak pulalah temannya"),
                $this->data_kalimat("302", "22", "اِجْهَدْ وَ لاَ تَكْسَلْ وَ لاَ تَكُ غَافِلاً فَنَدَامَةُ العُقْبىَ لِمَنْ يَتَكاَسَلُ", "Bersungguh-sungguhlah dan jangan bermalas-malas dan jangan pula lengah, karena penyesalan itu bagi orang yang bermalas-malas"),
                $this->data_kalimat("303", "22", "لاَ تُؤَخِّرْ عَمَلَكَ إِلىَ الغَدِ مَا تَقْدِرُ أَنْ تَعْمَلَهُ اليَوْمَ", "Janganlah mengakhirkan pekerjaanmu hingga esok hari, yang kamu dapat mengejakannya hari ini"),
                $this->data_kalimat("304", "22", "اُتْرُكِ الشَّرَّ يَتْرُكْكَ", "Tinggalkanlah kejahatan, niscaya ia (kejahatan itu) akan meninggalkanmu"),
                $this->data_kalimat("305", "22", "خَيْرُ النَّاسِ أَحْسَنُهُمْ خُلُقاً وَ أَنْفَعُهُمْ لِلنَّاسِ", "Sebaik-baik manusia itu, adalah yang terlebih baik budi pekertinya dan yang lebih bermanfaat bagi manusia"),
                $this->data_kalimat("306", "22", "فيِ التَّأَنِّي السَّلاَمَةُ وَ فيِ العَجَلَةِ النَّدَامَةُ", "di dalam hati-hati itu adanya keselamatan, dan di dalam tergesa-gesa itu adanya penyesalan"),
                $this->data_kalimat("307", "22", "ثَمْرَةُ التَّفْرِيْطِ النَّدَامَةُ وَ ثَمْرَةُ الحَزْمِ السَّلاَمَةُ", "Buah sembrono/lengah itu penyesalan, dan buah cermat itu keselamatan"),
                $this->data_kalimat("308", "22", "الرِّفْقُ بِالضَّعِيْفِ مِنْ خُلُقِ الشَّرِيْفِ", "Berlemah lembut kepada orang yang lemah itu, adalah suatu perangai orang yang mulia"),
                $this->data_kalimat("309", "22", "فَجَزَاءُ سَيِّئَةٍ سَيِّئَةٌ مِثْلُهَا", "Pahala/imbalan suatu kejahatan itu adalah kejahatan yang sama dengannya"),
                
                $this->data_kalimat("310", "23", "تَرْكُ الجَوَابِ عَلىَ الجَاهِلِ جَوَابٌ", "Tidak menjawab terhadap orang yang bodoh itu adalah jawabannya"),
                $this->data_kalimat("311", "23", "مَنْ عَذُبَ لِسَانُهُ كَثُرَ إِخْوَانُهُ", "Barang siapa manir tutur katanya (perkataannya) banyaklah temannya"),
                $this->data_kalimat("312", "23", "إِذَا تَمَّ العَقْلُ قَلَّ الكَلاَمُ", "Apabila akal seseorang telah sempurna maka sedikitlah bicaranya"),
                $this->data_kalimat("313", "23", "مَنْ طَلَبَ أَخًا بِلاَ عَيْبٍ بَقِيَ بِلاَ أَخٍ", "Barang siapa mencari teman yang tidak bercela, maka ia akan tetap tidak mempunyai teman"),
                $this->data_kalimat("314", "23", "قُلِ الحَقَّ وَلَوْ كَانَ مُرًّا", "Katakanlah yang benar itu, walaupun pahit"),
                $this->data_kalimat("315", "23", "خَيْرُ مَالِكَ مَا نَفَعَكَ", "Sebaik-baik hartamu adalah yang bermanfaat bagimu"),
                $this->data_kalimat("316", "23", "خَيْرُ الأُمُوْرِ أَوْسَطُهَا", "Sebaik-baik perkara itu adalah pertengahanya"),
                $this->data_kalimat("317", "23", "لِكُلِّ مَقَامٍ مَقَالٌ وَ لِكُلِّ مَقَالٍ مَقَامٌ", "Tiap-tiap tempat ada kata-katanya yang tepat, dan pada setiap kata ada tempatnya yang tepat"),
                $this->data_kalimat("318", "23", "إِذاَ لَمْ تَسْتَحْيِ فَاصْنَعْ مَا شِئْتَ", "Apabila engkau tidak malu, maka berbuatlah sekehendakmu"),
                $this->data_kalimat("319", "23", "لَيْسَ العَيْبُ لِمَنْ كَانَ فَقِيْرًا بَلِ العَيْبُ لِمَنْ كَانَ بَخِيْلاً", "Bukanlah cela itu bagi orang yang miskin, tapi cela itu terletak pada orang yang kikir"),
                $this->data_kalimat("320", "23", "لَيْسَ اليَتِيْمُ الَّذِي قَدْ مَاتَ وَالِدُهُ بَلِ اليَتِيْمُ يَتِيْمُ العِلْمِ وَ الأَدَبِ", "Bukanlah anak yatim itu yang telah meninggal orang tuanya, tapi (sebenarnya) yatim itu adalah yatim ilmu dan budi pekerti"),
                
                $this->data_kalimat("321", "24", "لِكُلِّ عَمَلٍ ثَوَابٌ وَ لِكُلِّ كَلاَمٍ جَوَابٌ", "Setiap pekerjaan itu ada upahnya, dan setiap perkataan itu ada jawabannya"),
                $this->data_kalimat("322", "24", "وَ عَامِلِ النَّاسَ بِمَا تُحِبُّ مِنْهُ دَائِماً", "Dan pergaulilah manusia itu dengan apa-apa yang engkau sukai daripada mereka semuanya"),
                $this->data_kalimat("323", "24", "هَلَكَ امْرُؤٌ لَمْ يَعْرِفْ قَدْرَهُ", "Hancurlah seseorang yang tidak tahu dirinya sendiri"),
                $this->data_kalimat("324", "24", "رَأْسُ الذُّنُوْبِ الكَذِبُ", "Pokok dosa itu, adalah kebohongan"),
                $this->data_kalimat("325", "24", "مَنْ ظَلَمَ ظُلِمَ", "Barang siapa menganiaya niscaya akan dianiaya"),
                $this->data_kalimat("326", "24", "لَيْسَ الجَمَالُ بِأَثْوَابٍ تُزَيِّنُنُا إِنَّ الجَمَالَ جمَاَلُ العِلْمِ وَ الأَدَبِ", "Bukanlah kecantikan itu dengan pakaian yang menghias kita, sesungguhnya kecantikan itu ialah kecantikan dengan ilmu dan kesopanan"),
                $this->data_kalimat("327", "24", "لاَ تَكُنْ رَطْباً فَتُعْصَرَ وَ لاَ يَابِسًا فَتُكْسَرَ", "janganlah engkau bersikap lemah, sehingga kamu akan diperas, dan janganlah kamu bersikap keras, sehingga kamu akan dipatahkan"),
                $this->data_kalimat("328", "24", "مَنْ أَعاَنَكَ عَلىَ الشَّرِّ ظَلَمَكَ", "Barang siapa menolongmu dalam kejahatan maka ia telah menyiksamu"),
            ];

            return $data;
        }

        public function data_kalimat($id, $tema, $kalimat, $arti, $indo = "", $arab = ""){
            $data = [
                "id" => $id,
                "tema" => $tema,
                "kalimat" => $kalimat,
                "arti" => $arti,
                "kata_arab" => array_unique($this->kata($kalimat, $arab)),
                "kata_indo" => array_unique($this->kata($arti, $indo)),
                "status" => "on"
            ];

            return $data;
        }

        public function kata($kata, $sum = ""){
            $kata = explode(" ", $kata);
            if($sum){
                $tambahan = explode(" ", $sum);
                foreach ($tambahan as $data) {
                    $kata[] = $data;
                }
            }
            // $kata[] = "_";
            return $kata;
        }

        public function tema(){
            $data = [
                $this->data_tema("1", "", "1", "2", "الحصة الأولى", "Bagian 1", "15"),
                $this->data_tema("1", "1", "2", "3", "الحصة الثانية", "Bagian 2", "15"),
                $this->data_tema("1", "2", "3", "4", "الحصة الثالثة", "Bagian 3", "15"),
                $this->data_tema("1", "3", "4", "5", "الحصة الرابعة", "Bagian 4", "10"),
                $this->data_tema("1", "4", "5", "6", "الحصة الخامسة", "Bagian 5", "15"),
                $this->data_tema("1", "5", "6", "7", "الحصة السادسة", "Bagian 6", "15"),
                $this->data_tema("1", "6", "7", "8", "الحصة السابعة", "Bagian 7", "15"),
                $this->data_tema("1", "7", "8", "9", "الحصة الثامنة", "Bagian 8", "15"),
                $this->data_tema("1", "8", "9", "10", "الحصة التاسعة", "Bagian 9", "15"),
                $this->data_tema("1", "9", "10", "11", "الحصة العاشرة", "Bagian 10", "15"),
                $this->data_tema("1", "10", "11", "12", "الحصة الحادية عشرة", "Bagian 11", "15"),
                $this->data_tema("1", "11", "12", "13", "الحصة الثانية عشرة", "Bagian 12", "15"),
                $this->data_tema("1", "12", "13", "14", "الحصة الثالثة عشرة", "Bagian 13", "15"),
                $this->data_tema("1", "13", "14", "15", "الحصة الرابعة عشرة", "Bagian 14", "15"),
                $this->data_tema("1", "14", "15", "16", "الحصة الخامسة عشرة", "Bagian 15", "15"),
                $this->data_tema("1", "15", "16", "17", "الحصة السادسة عشرة", "Bagian 16", "15"),
                $this->data_tema("1", "16", "17", "18", "الحصة السابعة عشرة", "Bagian 17", "15"),
                $this->data_tema("1", "17", "18", "19", "الحصة الثامنة عشرة", "Bagian 18", "15"),
                $this->data_tema("1", "18", "19", "20", "المحفوظات ١", "Bagian 19", "12"),
                $this->data_tema("1", "19", "20", "21", "المحفوظات ٢", "Bagian 20", "12"),
                $this->data_tema("1", "20", "21", "22", "المحفوظات ٣", "Bagian 21", "11"),
                $this->data_tema("1", "21", "22", "23", "المحفوظات ٤", "Bagian 22", "9"),
                $this->data_tema("1", "22", "23", "24", "المحفوظات ٥", "Bagian 23", "11"),
                $this->data_tema("1", "23", "24", "", "المحفوظات ٦", "Bagian 24", "8"),
                
            ];

            return $data;
        }

        public function data_tema($buku, $back, $id, $next, $tema, $tema_in, $count){
            $data = [
                "buku" => $buku,
                "back" => $back,
                "id" => $id,
                "next" => $next,
                "tema" => $tema,
                "tema_in" => $tema_in,
                "count" => $count
            ];

            return $data;
        }
    }
?>